/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MentorIndexRouteImport } from './routes/mentor.index'
import { Route as MentorStudentsRouteImport } from './routes/mentor.students'
import { Route as MentorProfileRouteImport } from './routes/mentor.profile'
import { Route as MentorCalendarRouteImport } from './routes/mentor.calendar'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppMentorsRouteImport } from './routes/_app.mentors'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorIndexRoute = MentorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MentorRoute,
} as any)
const MentorStudentsRoute = MentorStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => MentorRoute,
} as any)
const MentorProfileRoute = MentorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MentorRoute,
} as any)
const MentorCalendarRoute = MentorCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => MentorRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMentorsRoute = AppMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRouteWithChildren
  '/signup': typeof SignupRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/mentors': typeof AppMentorsRoute
  '/profile': typeof AppProfileRoute
  '/mentor/calendar': typeof MentorCalendarRoute
  '/mentor/profile': typeof MentorProfileRoute
  '/mentor/students': typeof MentorStudentsRoute
  '/mentor/': typeof MentorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/calendar': typeof AppCalendarRoute
  '/dashboard': typeof AppDashboardRoute
  '/mentors': typeof AppMentorsRoute
  '/profile': typeof AppProfileRoute
  '/mentor/calendar': typeof MentorCalendarRoute
  '/mentor/profile': typeof MentorProfileRoute
  '/mentor/students': typeof MentorStudentsRoute
  '/mentor': typeof MentorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/mentor': typeof MentorRouteWithChildren
  '/signup': typeof SignupRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/mentors': typeof AppMentorsRoute
  '/_app/profile': typeof AppProfileRoute
  '/mentor/calendar': typeof MentorCalendarRoute
  '/mentor/profile': typeof MentorProfileRoute
  '/mentor/students': typeof MentorStudentsRoute
  '/mentor/': typeof MentorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/mentor'
    | '/signup'
    | '/calendar'
    | '/dashboard'
    | '/mentors'
    | '/profile'
    | '/mentor/calendar'
    | '/mentor/profile'
    | '/mentor/students'
    | '/mentor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/calendar'
    | '/dashboard'
    | '/mentors'
    | '/profile'
    | '/mentor/calendar'
    | '/mentor/profile'
    | '/mentor/students'
    | '/mentor'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/login'
    | '/mentor'
    | '/signup'
    | '/_app/calendar'
    | '/_app/dashboard'
    | '/_app/mentors'
    | '/_app/profile'
    | '/mentor/calendar'
    | '/mentor/profile'
    | '/mentor/students'
    | '/mentor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  MentorRoute: typeof MentorRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/': {
      id: '/mentor/'
      path: '/'
      fullPath: '/mentor/'
      preLoaderRoute: typeof MentorIndexRouteImport
      parentRoute: typeof MentorRoute
    }
    '/mentor/students': {
      id: '/mentor/students'
      path: '/students'
      fullPath: '/mentor/students'
      preLoaderRoute: typeof MentorStudentsRouteImport
      parentRoute: typeof MentorRoute
    }
    '/mentor/profile': {
      id: '/mentor/profile'
      path: '/profile'
      fullPath: '/mentor/profile'
      preLoaderRoute: typeof MentorProfileRouteImport
      parentRoute: typeof MentorRoute
    }
    '/mentor/calendar': {
      id: '/mentor/calendar'
      path: '/calendar'
      fullPath: '/mentor/calendar'
      preLoaderRoute: typeof MentorCalendarRouteImport
      parentRoute: typeof MentorRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mentors': {
      id: '/_app/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof AppMentorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMentorsRoute: typeof AppMentorsRoute
  AppProfileRoute: typeof AppProfileRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMentorsRoute: AppMentorsRoute,
  AppProfileRoute: AppProfileRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MentorRouteChildren {
  MentorCalendarRoute: typeof MentorCalendarRoute
  MentorProfileRoute: typeof MentorProfileRoute
  MentorStudentsRoute: typeof MentorStudentsRoute
  MentorIndexRoute: typeof MentorIndexRoute
}

const MentorRouteChildren: MentorRouteChildren = {
  MentorCalendarRoute: MentorCalendarRoute,
  MentorProfileRoute: MentorProfileRoute,
  MentorStudentsRoute: MentorStudentsRoute,
  MentorIndexRoute: MentorIndexRoute,
}

const MentorRouteWithChildren =
  MentorRoute._addFileChildren(MentorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  MentorRoute: MentorRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
